### PR TITLE
20 remove calls to cli functions

### LINKED ISSUE #20: Remove calls to {cli} functions
Rigorous and extensive testing of `posit-workbench-job-scheduler` has revealed that calls to functions in the `{cli}` package (e.g. `cli::cli_inform()`) pause execution in an interactive Posit Workbench session. if that session is not open and connected to from a web browser.

`cli::cli_inform()` has been used extensively in this project to output messages to the user about scheduling activity.  These messages will need to be output using an alternative method.

Current thinking is that the safest method is to log these messages to file, rather than the R console, but with the disadvantage of not being as user friendly.

### PR DESCRIPTION
**Pull request by terrymclaughlin**
# Pull Request Details

Issue Number: Closes #20 
Type: Bug :bug:

## Description of the Change

- Removes {cli} from the project's renv environment
- Replaces {cli} function calls with base R alternatives for writing to the console, such that these execute in an interactive Posit Workbench session when not connected to with a web browser.
- Enhances testing of error handling by the functions that launch and schedule Workbench Jobs, and cancel schedules.

### CODE REVIEW

**Comment by terrymclaughlin** [comment]
@jakeybob and @rmccreath 

I'd appreciate if you were able to try scheduling with this version of `posit-workbench-job-scheduler` to make sure that jobs are scheduled at (roughly) the right time, and __specifically__  whilst the Posit Workbench session is not open in a web browser.

**Comment by terrymclaughlin** [comment]
Just to add that there's no change to the original intended functionality, and messages reported to users are effectively the same.  It's just all implemented without `{cli}` now.

**Comment by jakeybob** [comment]
I used this branch to run lots of jobs on a five min schedule, and then tested with simultaneous 1hr and 3hr jobs (in different sessions) overnight (with browser tabs etc closed, laptop shut down for good measure lol). All the above jobs ran successfully, launched at the correct times, and did not suffer from the 2 hour timeout, the 2 *job* timeout, or the interactive session effects we've been seeing.

Looks like all these issues are now fixed; happy to merge 😄

**Comment by jakeybob** [comment]
A small point to note is that the job start time slips forward by about one second for every two jobs, which I think is inevitable (subsequent job start times can only ever slip later, and start times of current jobs are subject to integer rounding etc). I don't think this is a dealbreaker in any way: I only really noticed it because I was scheduling jobs every 5 minutes, and daily jobs should only slip by a minute over two months. But, worth keeping in mind.

**Review by jakeybob — APPROVED** [review]

**Comment by terrymclaughlin** [comment]
@jakeybob I've opened an issue for the job start time slipping forward by about one second for every two jobs, so that we don't forget about it (in case we want to fix it).

**Comment by terrymclaughlin** [comment]
@jakeybob Thanks very much for testing this, and I'm glad we've got to the bottom of this issue.  I've had one more issue raised with the proxy not being set within a Workbench Job, so if the script tries to connect to the internet, it fails.  This is issue #22 which I'm going to work on now.

**Pull request merged**
